version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
      - image: cimg/base:2022.09
        name: secondary
    steps:
      - run: "ls"
      - run: sudo apt-get update && sudo apt-get install -y netcat
      - run: which nc
      # - run: docker network ls
      - run: ping secondary
      # - run: nc -vz localhost 3306

workflows: null
