version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base
      - image: cimg/base
        name: secondary
    steps:
      - run: "ls"
      - run: sudo apt-get update && sudo apt-get install -y nc
      - run: which nc
      # - run: docker network ls
      # - run: ping
      # - run: nc -vz localhost 3306

workflows: null
