version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
    # Primary container image where all steps run.
      - image: cimg/base:current
        name: primaryA1
    # Secondary container image on common network.
      - image: cimg/base:current
        name: secondary
        command: /bin/bash -c 'sleep 5 && sudo apt-get update && sudo apt-get install -y netcat && nc randomhost 80'
        # nc: getaddrinfo for host "primaryA1" port 80: Name or service not known
    resource_class: small
    steps:
      - run: "ls"
      - run: sudo apt-get update && sudo apt-get install -y netcat iputils-ping dnsutils
      - run: sleep 30
      # - run: nslookup secondary
      # - run: ping secondary
      # - run: nc -vz secondary 80
      # nc: connect to secondary (192.168.208.4) port 80 (tcp) failed: Connection refused
      # - run: nc -vz random 80
      # nc: getaddrinfo for host "random" port 80: Name or service not known

workflows: null
